#!/usr/bin/env bash

ICONS="$HOME/.config/hypr/icons"

get_volume() {
    wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print int($2 * 100)}'
}

get_icon() {
	local current=$(get_volume)
    if (( current == 0 )); then
        echo "$ICONS/volume-mute.png"
    elif (( current <= 30 )); then
        echo "$ICONS/volume-low.png"
    elif (( current <= 60 )); then
        echo "$ICONS/volume-mid.png"
    else
        echo "$ICONS/volume-high.png"  # covers 61–100+ 
    fi
}

send_notification() {
    local icon=$1
    local message=$2
	notify-send \
        -h string:x-canonical-private-synchronous:sys-notify \
        -u low \
        -i "$icon" \
        "$message"
}

inc_volume() {
    wpctl set-mute @DEFAULT_AUDIO_SINK@ 0
    wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
    send_notification "$(get_icon)" "Volume : $(get_volume)%" 

}

dec_volume() {
    wpctl set-mute @DEFAULT_AUDIO_SINK@ 0
    wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
    send_notification "$(get_icon)" "Volume : $(get_volume)%" 
}

toggle_mute() {
    wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

    if wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -q 'MUTED'; then
        send_notification "$ICONS/volume-mute.png" "Volume Switched OFF"
    else
        send_notification "$(get_icon)" "Volume Switched ON"
    fi
}

toggle_mic() {
    wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

    if wpctl get-volume @DEFAULT_AUDIO_SOURCE@ | grep -q 'MUTED'; then
        send_notification "$ICONS/microphone-mute.png" "Microphone Switched OFF"
    else
        send_notification "$ICONS/microphone.png" "Microphone Switched ON"
    fi
}

case "$1" in
    --inc) inc_volume;;
    --dec) dec_volume;;
    --toggle) toggle_mute;;
    --toggle-mic) toggle_mic;;
esac

